# Generated by Django 4.1.9 on 2023-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id-images/'),
        ),
    ]
